catalogMode: prefer
shellEmulator: true

packages:
  - docs
  - playground
  - packages/**
  - examples/**

catalogs:
  build:
    "@vitejs/plugin-vue": ^6.0.3
    tsdown: ^0.17.4
    vite: ^7.2.7
  cli:
    "@antfu/ni": ^28.0.0
    bumpp: ^10.3.2
    pncat: ^0.7.7
  dev:
    "@vue/runtime-core": ^3.5.25
  frontend:
    ress: ^5.0.2
    vue: ^3.5.25
  lint:
    "@antfu/eslint-config": ^6.7.1
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    stylelint: ^16.26.1
    stylelint-config-recess-order: ^7.4.0
    stylelint-order: ^7.0.0
    stylelint-scss: ^6.13.0
  node:
    local-pkg: ^1.1.2
  script:
    esno: ^4.8.0
  style:
    postcss-html: ^1.8.0
    postcss-scss: ^4.0.9
  test:
    vitest: ^4.0.15
  tsc:
    typescript: ~5.9.3
    vue-tsc: ^3.1.8
  types:
    "@types/node": ^22.19.3
  utils:
    es-toolkit: ^1.43.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks