packages:
  - docs
  - playground
  - packages/**
  - examples/**
catalogs:
  build:
    "@vitejs/plugin-vue": ^6.0.2
    tsdown: ^0.16.5
    vite: ^7.2.2
  cli:
    "@antfu/ni": ^27.0.1
    bumpp: ^10.3.1
    pncat: ^0.7.6
  dev:
    "@vue/runtime-core": ^3.5.24
  frontend:
    ress: ^5.0.2
    vue: ^3.5.24
  lint:
    "@antfu/eslint-config": ^6.2.0
    eslint: ^9.39.1
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    stylelint: ^16.25.0
    stylelint-config-recess-order: ^7.4.0
    stylelint-order: ^7.0.0
    stylelint-scss: ^6.12.1
  node:
    local-pkg: ^1.1.2
  script:
    esno: ^4.8.0
  style:
    postcss-html: ^1.8.0
    postcss-scss: ^4.0.9
  test:
    vitest: ^4.0.10
  tsc:
    typescript: ~5.9.3
    vue-tsc: ^3.1.4
  types:
    "@types/node": ^22.19.1
  utils:
    es-toolkit: ^1.42.0
onlyBuiltDependencies:
  - esbuild
  - pncat
  - simple-git-hooks