shellEmulator: true
trustPolicy: no-downgrade

packages:
  - docs
  - playground
  - packages/**
  - examples/**

overrides:
  eslint: 9.39.4

catalogs:
  build:
    "@vitejs/plugin-vue": ^6.0.4
    tsdown: ^0.21.1
    vite: ^7.3.1
  cli:
    "@antfu/ni": ^28.3.0
    bumpp: ^10.4.1
    pncat: ^0.10.4
  frontend:
    "@vue/runtime-core": ^3.5.30
    vue: ^3.5.30
  lint:
    "@antfu/eslint-config": ~7.7.0
    eslint: ^9.39.4
    lint-staged: ^16.3.2
    simple-git-hooks: ^2.13.1
    stylelint: ^17.4.0
    stylelint-config-recess-order: ^7.6.1
    stylelint-order: ^7.0.1
    stylelint-scss: ^7.0.0
  node:
    local-pkg: ^1.1.2
  script:
    esno: ^4.8.0
  style:
    postcss-html: ^1.8.1
    postcss-scss: ^4.0.9
    ress: ^5.0.2
  test:
    vitest: ^4.0.18
  tsc:
    typescript: ~5.9.3
    vue-tsc: ^3.2.5
  types:
    "@types/node": ^24.12.0
  utils:
    es-toolkit: ^1.45.1

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks