shellEmulator: true
trustPolicy: no-downgrade

packages:
  - docs
  - playground
  - packages/**
  - examples/**

overrides:
  eslint: 9.39.3

catalogs:
  build:
    "@vitejs/plugin-vue": ^6.0.4
    tsdown: ^0.20.3
    vite: ^7.3.1
  cli:
    "@antfu/ni": ^28.2.0
    bumpp: ^10.4.1
    pncat: ^0.10.2
  frontend:
    "@vue/runtime-core": ^3.5.29
    vue: ^3.5.29
  lint:
    "@antfu/eslint-config": ~7.6.1
    eslint: ^9.39.3
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    stylelint: ^17.4.0
    stylelint-config-recess-order: ^7.6.1
    stylelint-order: ^7.0.1
    stylelint-scss: ^7.0.0
  node:
    local-pkg: ^1.1.2
  script:
    esno: ^4.8.0
  style:
    postcss-html: ^1.8.1
    postcss-scss: ^4.0.9
    ress: ^5.0.2
  test:
    vitest: ^4.0.18
  tsc:
    typescript: ~5.9.3
    vue-tsc: ^3.2.5
  types:
    "@types/node": ^24.10.14
  utils:
    es-toolkit: ^1.44.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks